apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        name: postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.env.POSTGRES_USER | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.env.POSTGRES_PASSWORD | quote }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}