apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: "redis-service"
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
  selector:
    app: redis